[2024-07-08T17:20:20.448+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-08T17:20:21.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-07-08T17:20:21.325+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-24T00:00:00+00:00 [queued]>
[2024-07-08T17:20:21.355+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-08T17:20:21.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2024-06-24 00:00:00+00:00
[2024-07-08T17:20:22.010+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'scheduled__2024-06-24T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpzzx67_z9']
[2024-07-08T17:20:22.025+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask insert_book_data
[2024-07-08T17:20:21.994+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=273) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-08T17:20:22.059+0000] {standard_task_runner.py:63} INFO - Started process 292 to run task
[2024-07-08T17:20:24.529+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data scheduled__2024-06-24T00:00:00+00:00 [running]> on host 75379950ed90
[2024-07-08T17:20:28.792+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-24T00:00:00+00:00'
[2024-07-08T17:20:29.110+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-08T17:20:30.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-08T17:20:30.208+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2024-07-08T17:20:30.974+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=scheduled__2024-06-24T00:00:00+00:00, execution_date=20240624T000000, start_date=20240708T172021, end_date=20240708T172030
[2024-07-08T17:20:31.517+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task insert_book_data (No book data found; 292)
[2024-07-08T17:20:32.053+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-08T17:20:32.564+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
